quarkus.http.port=8080
portal.nats.url=nats://localhost:4222
portal.execute.subject=portal.execute
portal.execute.timeout=PT30S

quarkus.datasource.db-kind=mariadb
quarkus.datasource.username=portal
quarkus.datasource.password=portal
quarkus.datasource.jdbc.url=jdbc:mariadb://localhost:3307/portal
